databases:
  - name: Fail_Share
    databaseName: Fail_Share
    user: Fail_Share
    region: singapore

services:
  - type: web
    name: Fail_Share
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fail_share
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

